package com.okrur.st.mj.util;

public class RestUtil {
	public static String SUCCESS = "1";
	public static String ERROR = "0";
	public static String DUPLICATE = "2";
	public static String SUCCESSFUL_MESSAGE = "Successful";
	public static String CREDENTIAL_ERROR_MESSAGE = "Invalid username or password";
	public static String UNEXPECTED_ERROR = "Unexpected error!";
	public static String ALREADY_EXIST_MESSAGE = "Already exist!";
	public static String REQUEST_TYPE_FEE_APPLY = "REQUEST_TYPE_FEE_APPLY";
	public static String REQUEST_TYPE_CREATE = "REQUEST_TYPE_CREATE";
	public static String REQUEST_TYPE_FEE_SETUP_ENGINE = "SETUP_ENGINE";
	public static String REQUEST_TYPE_FILE_UPLOAD = "REQUEST_TYPE_FILE_UPLOAD";
	public static String REQUEST_TYPE_UPDATE = "REQUEST_TYPE_UPDATE";
	public static String REQUEST_TYPE_DELETE = "REQUEST_TYPE_DELETE";
	public static String REQUEST_TYPE_DETAILS = "REQUEST_TYPE_DETAILS";
	public static String REQUEST_TYPE_LIST = "REQUEST_TYPE_LIST";
	public static String REQUEST_TYPE_SEARCH = "REQUEST_TYPE_SEARCH";
	public static String REQUEST_TYPE_FIND = "REQUEST_FIND";
	public static String MODULE_RIGHT = "MODULE_RIGHT";
	public static String MODULE_ROLE = "MODULE_ROLE";
	public static String MODULE_EDUCATION_TYPE = "MODULE_EDUCATION_TYPE";
	public static String MODULE_FEE = "MODULE_FEE";
	public static String MODULE_GRADE_POINT = "MODULE_GRADE_POINT";
	public static String MODULE_GRADE = "MODULE_GRADE";
	public static String MODULE_GRADING_SYSTEM = "MODULE_GRADING_SYSTEM";
	public static String MODULE_INSTITUTE = "MODULE_INSTITUTE";
	public static String MODULE_INSTITUTE_EDUCATION_TYPE = "MODULE_INSTITUTE_EDUCATION_TYPE";
	public static String MODULE_DONOR = "MODULE_DONOR";
	public static String MODULE_EXPENDITURE = "MODULE_EXPENDITURE";
	public static String MODULE_FINANCIAL_REPORTS = "MODULE_FINANCIAL_REPORTS";
	public static String MODULE_UDV = "MODULE_UDV";
	public static String MODULE_ORGANIZATION = "MODULE_ORGANIZATION";
	public static String MODULE_STUDENT_ACTIVITY = "MODULE_STUDENT_ACTIVITY";
	public static String MODULE_STUDENT = "MODULE_STUDENT";
	public static String MODULE_TRANSACTION_HISTORY = "MODULE_TRANSACTION_HISTORY";
	public static String MODULE_USER = "MODULE_USER";
	public static String MODULE_TEACHER = "MODULE_TEACHER";
	public static String MODULE_EDUCATION_TYPE_GRADE = "MODULE_EDUCATION_TYPE_GRADE";
	public static String MODULE_EDUCATION_TYPE_GRADING_SYSTEM="MODULE_EDUCATION_TYPE_GRADING_SYSTEM";
	public static String MODULE_STUDENT_FEE="MODULE_STUDENT_FEE";
	public static String MODULE_TRANSACTION="MODULE_TRANSACTION";
	public static String MODULE_FEE_COLLECTION = "MODULE_FEE_COLLECTION";
	public static String MODULE_DASHBOARD = "MODULE_DASHBOARD";
	public static String MODULE_INCOME = "MODULE_INCOME";
	
	public static String REQUEST_TYPE_USER_LOGIN = "REQUEST_TYPE_USER_LOGIN";
	public static String AUTHENTICATION_ERROR_MESSAGE = "Authentication failed";
	public static String SCHOOL_NOT_FOUND_ERROR_MESSAGE = "School not found!";
	public static String DUPLICATE_USER_NAME="This user name already exist";
	public static String COLUMN_NAMES = "Reports_management_column_names";
}
