package com.okrur.st.mj.data.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.Size;

import com.okrur.st.mj.rest.model.UdvModel;

/**
 * @File Udv.java: Udv database entity 
 * @author shaiful islam palash | kuvic16@gmail.com
 * @CreationDate Nov 24, 2015
 */
@Entity
@Table(name = "udv")
public class Udv extends AuditableEntity implements Serializable {
    
    private static final long serialVersionUID = -4643440779839366748L;
    
    @Column(name = "parent_id")
    private String parentId;
    
    @Size(max = 250)
    @Column(name = "parent_category")
    private String parentCategory;

	@Size(max = 250)
    @Column(name = "category")
    private String category;
	
    @Size(max = 250)
    @Column(name = "value")
    private String value;
    
    @Size(max = 250)
    @Column(name = "alt_value")
    private String altValue;
    
    @Size(max = 1000)
    @Column(name = "description")
    private String description;
        
    @Size(max = 250)
    @Column(name="hierarchy_id")
    private String hierarchyId; // auto generated code: code generated by place id with hierarchy
    
    @Column(name = "status")
    private Boolean status = true;

	public String getParentId() {
		return parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getAltValue() {
		return altValue;
	}

	public void setAltValue(String altValue) {
		this.altValue = altValue;
	}

	public String getHierarchyId() {
		return hierarchyId;
	}

	public void setHierarchyId(String hierarchyId) {
		this.hierarchyId = hierarchyId;
	}

	public Boolean getStatus() {
		return status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}
	
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	public String getParentCategory() {
		return parentCategory;
	}

	public void setParentCategory(String parentCategory) {
		this.parentCategory = parentCategory;
	}

	@Override
	public String getObjCode() {
		return "udv";
	}
	
	public Udv(){}
	public Udv setUdv(UdvModel model){
		this.setId(model.getId());
		this.setParentId(model.getParentId());
		this.setParentCategory(model.getParentCategory());
		this.setCategory(model.getCategory());
		this.setValue(model.getValue());
		this.setAltValue(model.getAltValue());
		this.setDescription(model.getDescription());
		this.setHierarchyId(model.getHierarchyId());
		return this;
	}
}
